name: CI Workflow for basic build and test

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ostad-runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Install dependencies
      - name: Install dependencies
        run: npm install --include=dev

      # Install Node types locally
      - name: Install Node types locally
        run: npm install -D @types/node

      # Build
      - name: Build
        run: npm run build

      # Run tests
      - name: Run tests
        run: npm run test

      # Show success message
      - name: Show success message
        run: echo "✅ Build and tests passed."
