name: CI Workflow for basic build and test

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ostad-runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Install global dependencies
      - name: Install global dependencies
        working-directory: ./myviteproject
        run: npm install -g typescript vite vitest

      # Build
      - name: Build
        working-directory: ./myviteproject
        run: npm run build

      # Run tests
      - name: Run tests
        working-directory: ./myviteproject
        run: npm run test

      # Show success message
      - name: Show success message
        run: echo "✅ Build and tests passed."
